name: Workflow Status
description: Validates another workflow's latest status
inputs:
  token:
    description: 'GITHUB_TOKEN'
    required: true
  workflow:
    description: 'The name of workflow'
    required: true
  repo:
    description: 'The repo that contains workflow'
    required: false
  branch:
    description: 'The branch to validate'
    required: false
    default: main
  event:
    description: 'The event to validate'
    required: false
  run:
    description: 'Can set "first" or "prev", default is "latest"'
    required: false
outputs:
  status:
    description: 'Workflow status'
  conclusion:
    description: 'Workflow conclusion'
runs:
  using: 'node12'
  main: 'dist/index.js'